apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: ci-cd
  labels:
    component: jenkins
spec:
  type: NodePort
  ports:
    - name: web
      port: 8080
      targetPort: 8080
    - name: slaves
      port: 50000
      targetPort: 50000 
  selector:
    component: jenkins
