apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: cicd
  labels:
    component: jenkins
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: jenkins
    spec:
      volumes:
        - name: jenkins-pv-storage
          persistentVolumeClaim:
            claimName: jenkins-pv-claim
      containers:
        - name: jenkins
          image: jnonino/jenkins-master
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "2048Mi"
              cpu: "2000m"
          ports:
            - name: web
              containerPort: 8080
            - name: slaves
              containerPort: 50000  
          envFrom:
            - configMapRef:
                name: jenkins-env-variables
          volumeMounts:
            - name: jenkins-pv-storage
              mountPath: "/var/jenkins_home"
